### ISSUE TITLE
Targeting iframe.html directly creates invalid hyperlinks

### ISSUE THREAD

**Issue by yuqu** [zeplin/cli-connect-storybook-plugin#19]
Hi @yuqu,
thank you. I just tried the most recent version and the `iframe.html` is no longer trimmed but unfortunately the generated url is still not valid.
The appended string starts with a `/` like:
`https://foobar/iframe.html/?selectedKind=foobar`

when removing the unexpected character everthing is working fine.
expected:
`https://foobar/iframe.html?selectedKind=foobar`

_Originally posted by @shortsn in https://github.com/zeplin/cli-connect-storybook-plugin/issues/7#issuecomment-616357185_

**Comment by yuqu** [comment]
@shortsn The trailing slash was there for another edge case and it created another bug for another edge case 😄 v0.1.9 is out now, check it out if the fix works for you.

**Comment by shortsn** [comment]
Thank you very much. I just updated all Zeplin dependencies and everything seems to work.
