### ISSUE TITLE
Storybook url is broken after sync

### ISSUE THREAD

**Issue by shortsn** [zeplin/cli-connect-storybook-plugin#7]
Hi,
i am running into an edge case where the storybook plugin breaks the url even though the sync seems to succeed.

Background:
We are accessing our intermediate builds of storybook using a TeamCity artifacts locator.
This allows to access files even in zip archives using a specific url pattern.
e.g.
**_[teamcity-build-locator]/storybook.zip!/iframe.html_**

Unfortunately the cli-plugin is trying to be smart and removes _**/iframe.html**_ which leads to urls like
_**[teamcity-build-locator]/storybook.zip!?selectedKind=foo&selectedStory=bar**_ that are no longer working.
https://github.com/zeplin/cli-connect-storybook-plugin/blob/a13c9c86e15fe12af8e1b6d3e4a557b9c943ebce/src/index.ts#L38-L40

I was able to workaround this by declaring my config url like **_<teamcity-build-locator>/storybook.zip!/iframe.html?_** but it feels dirty and might be worth fixing it.

**Comment by shortsn** [comment]
Hi,
unfortunately after updating from v0.1.4 to V0.1.6 the generated arguments charged in a way that the resulting url does no longer find the related story with my workaround.
the url is like `...iframe.html?/?selectedKind...`
Is there a chance to get rid of my workaround because I am currently unable to update from v0.1.4?

**Comment by shortsn** [comment]
Hi,
unfortunately when updating the plugin from `v0.1.4` to `v0.1.6` my workaround does no longer work and the integration becomes unusable for us.
Is there a chance to get this fixed because we are currently stuck on `v0.1.4`.

**Comment by yuqu** [comment]
@shortsn 

Sorry about hassle. I've decided that there is no reason to enforce trimming of iframe.html if the user really want to use it. The fix is published in version v0.1.7.

**Comment by shortsn** [comment]
Hi,
thank you. I just tried the most recent version and the `iframe.html` is no longer trimmed but unfortunately the generated url is still not valid.
The appended string starts with a `/` like:
`https://foobar/iframe.html/?selectedKind=foobar`

when removing the unexpected character everthing is working fine.
expected:
`https://foobar/iframe.html?selectedKind=foobar`
